import Navigation from "./components/Navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navLinks = [
    {
      name: 'Home',
      href: '/'
    },
    {
      name: 'Dashboard',
      href: '/dashboard'
    },
    {
      name: 'Blog',
      href: '/blog'
    }
  ]
  return (
    <html lang="en">
      <body>
        <Navigation navLinks={navLinks} />
        {children}
      </body>
    </html>
  )
}
